//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLDental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentOfUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AppointmentOfUser()
        {
            this.AppointmentOfClinics = new HashSet<AppointmentOfClinic>();
        }
    
        public string ID { get; set; }
        public string IDUser { get; set; }
        public System.DateTime Appt { get; set; }
        public System.DateTime NextAppt { get; set; }
        public int NoDelay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentOfClinic> AppointmentOfClinics { get; set; }
        public virtual User User { get; set; }
    }
}
